import type { Metadata } from 'next'
import '@/styles/global.scss'
import { poppins } from '@/fonts/fonts'
import { ReduxProvider } from '@/components/providers/ReduxProvider'
import Header from '@/components/widgets/layout/Header/Header'
import Footer from '@/components/widgets/layout/Footer/Footer'

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

interface RootLayoutProps {
	children: React.ReactNode
	params: { local: string }
}

export default function RootLayout({
	children,
	params: { local }
}: Readonly<RootLayoutProps>) {
	return (
		<html lang={local}>
			<body className={poppins.variable}>
				<ReduxProvider>
					<div className='wrapper'>
						<Header />
						<main className='main'>{children}</main>
						<Footer />
					</div>
				</ReduxProvider>
			</body>
		</html>
	)
}
