import type { Metadata } from 'next'
import '../../styles/global.scss'
// import { Poppins } from 'next/font/google'
import { poppins } from '@/fonts/fonts'


// const poppins = Poppins({
// 	weight: ['400', '500', '700'],
// 	subsets: ['latin'],
// 	variable: '--font-poppins',
// 	display: 'swap'
// })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

interface RootLayoutProps {
	children: React.ReactNode
	params: { local: string }
}

export default function RootLayout({
	children,
	params: { local }
}: Readonly<RootLayoutProps>) {
	return (
		<html lang={local}>
			<body className={poppins.variable}>{children}</body>
		</html>
	)
}
