import type { Metadata } from 'next'
import '@/styles/global.scss'
import { poppins } from '@/fonts/fonts'
import { ReduxProvider } from '@/components/providers/ReduxProvider'

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

interface RootLayoutProps {
	children: React.ReactNode
	params: { local: string }
}

export default function RootLayout({
	children,
	params: { local }
}: Readonly<RootLayoutProps>) {
	return (
		<html lang={local}>
			<body className={poppins.variable}>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	)
}
