// Header
export { default as LogoSite } from '@/icons/logo.svg'
export { default as UserIcon } from '@/icons/user.svg'
export { default as BurgerIcon } from '@/icons/burger.svg'
export { default as DeliveryIcon } from '@/icons/car_delivery.svg'
export { default as SearchIcon } from '@/icons/search.svg'
export { default as CompareIcon } from '@/icons/compare.svg'
export { default as FavoriteIcon } from '@/icons/favorite.svg'
export { default as CartIcon } from '@/icons/cart.svg'
export { default as CartIconThick } from '@/icons/cart-thick.svg'
export { default as StarIcon } from '@/icons/star.svg'
export { default as CommentIcon } from '@/icons/comment.svg'
export { default as FavoriteIconGreen } from '@/icons/favorite-green.svg'
export { default as CheckIcon } from '@/icons/check.svg'
export { default as TriangleIcon } from '@/icons/triangle.svg'
